<?php

namespace App\Http\Requests;

use App\Models\Enums\BackgroundColorType;
use App\Models\Enums\VoucherType;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ShopCustomTemplate extends Request
{
    /*
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'background_color' => ['nullable', Rule::in(BackgroundColorType::all())],
            'welcoming' => ['nullable', 'string', 'max:256']
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        $this->session()->put('tab', 'customs');

        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
